print(ord('B'))
print(ord('c'))
print(ord('D'))
print(ord('b'))
print(ord('c'))
print(ord('d'))
print(ord('o'))
print(ord('1'))
print(ord('2'))
print(ord('$'))
print(ord('*'))
print(ord('+'))
print(ord(' '))