print("        A        ")
print("       ABA       ")
print("      ABCBA      ")
print("     ABCDCBA     ")
print("    ABCDEDCBA    ")
print("   ABCDEFEDCBA   ")
print("  ABCDEFGFEDCBA  ")
print(" ABCDEF GF EDCBA ")
print("  ABCDEFGFEDCBA  ")
print("   ABCDEFEDCBA   ")
print("    ABCDEDCBA    ")
print("     ABCDCBA     ")
print("      ABCBA      ")
print("       ABA       ")
print("        A        ")